//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articles()
        {
            this.Comments = new HashSet<Comments>();
            this.Tags = new HashSet<Tags>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int CategoriesId { get; set; }
        public int WriterId { get; set; }
        public Nullable<int> PhotosId { get; set; }
        public int ViewCount { get; set; }
        public int LikeCount { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Photos Photos { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
