//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public int ArticlesId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string NameSurname { get; set; }
        public Nullable<int> LikeCount { get; set; }
    
        public virtual Articles Articles { get; set; }
    }
}
